spring:
  application:
    name: demo
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    username: root
    password: 1111
    driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapper/*.xml

server:
  port: 8081
